version: '3'
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf

  php:
    build: .
    volumes:
      - ./:/var/www/html
    links:
      - postgres
      - redis

  redis:
    image: redis
    ports: 
      - "6379:6379"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
