version: '3'
services:
  web:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php  

  php:
    build: .
    container_name: php
    volumes:
      - ./:/var/www/html
    links:
      # - postgres
      - redis

  redis:
    image: redis
    container_name: redis
    ports: 
      - "6379:6379"

  # postgres:
  #   image: postgres
  #   container_name: postgres
  #   ports:
  #     - "5432:5432"
